var annotated =
[
    [ "App", "class_app.html", "class_app" ],
    [ "AppExisteNoCarrinho", "class_app_existe_no_carrinho.html", "class_app_existe_no_carrinho" ],
    [ "AppInexistente", "class_app_inexistente.html", "class_app_inexistente" ],
    [ "AppJaExiste", "class_app_ja_existe.html", "class_app_ja_existe" ],
    [ "AppStore", "class_app_store.html", "class_app_store" ],
    [ "BinaryNode", "class_binary_node.html", "class_binary_node" ],
    [ "BST", "class_b_s_t.html", "class_b_s_t" ],
    [ "BSTItrIn", "class_b_s_t_itr_in.html", "class_b_s_t_itr_in" ],
    [ "BSTItrLevel", "class_b_s_t_itr_level.html", "class_b_s_t_itr_level" ],
    [ "BSTItrPost", "class_b_s_t_itr_post.html", "class_b_s_t_itr_post" ],
    [ "BSTItrPre", "class_b_s_t_itr_pre.html", "class_b_s_t_itr_pre" ],
    [ "Cliente", "class_cliente.html", "class_cliente" ],
    [ "ClienteInexistente", "class_cliente_inexistente.html", "class_cliente_inexistente" ],
    [ "ClienteJaExiste", "class_cliente_ja_existe.html", "class_cliente_ja_existe" ],
    [ "Comentario", "struct_comentario.html", "struct_comentario" ],
    [ "Date", "class_date.html", "class_date" ],
    [ "Developer", "class_developer.html", "class_developer" ],
    [ "Developer_Empresa", "class_developer___empresa.html", "class_developer___empresa" ],
    [ "Developer_Individual", "class_developer___individual.html", "class_developer___individual" ],
    [ "developerH", "structdeveloper_h.html", "structdeveloper_h" ],
    [ "DeveloperInexistente", "class_developer_inexistente.html", "class_developer_inexistente" ],
    [ "DeveloperJaExiste", "class_developer_ja_existe.html", "class_developer_ja_existe" ],
    [ "FileIOException", "class_file_i_o_exception.html", "class_file_i_o_exception" ],
    [ "InvalidParameter", "class_invalid_parameter.html", "class_invalid_parameter" ],
    [ "PermissoesInsuficientes", "class_permissoes_insuficientes.html", "class_permissoes_insuficientes" ],
    [ "Rating", "class_rating.html", "class_rating" ],
    [ "Sale", "class_sale.html", "class_sale" ],
    [ "sortQueue", "structsort_queue.html", "structsort_queue" ]
];